---
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: 'utf8'
        types:
            uuid: App\EconumoBundle\Infrastructure\Doctrine\Type\UuidType
            account_type: App\EconumoBundle\Infrastructure\Doctrine\Type\AccountType
            account_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\AccountNameType
            account_user_role_type: App\EconumoBundle\Infrastructure\Doctrine\Type\AccountUserRoleType
            category_type: App\EconumoBundle\Infrastructure\Doctrine\Type\CategoryType
            category_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\CategoryNameType
            transaction_type: App\EconumoBundle\Infrastructure\Doctrine\Type\TransactionType
            icon_type: App\EconumoBundle\Infrastructure\Doctrine\Type\IconType
            folder_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\FolderNameType
            connection_code_type: App\EconumoBundle\Infrastructure\Doctrine\Type\ConnectionCodeType
            currency_code_type: App\EconumoBundle\Infrastructure\Doctrine\Type\CurrencyCodeType
            payee_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\PayeeNameType
            tag_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\TagNameType
            user_role_type: App\EconumoBundle\Infrastructure\Doctrine\Type\UserRoleType
            user_password_request_code_type: App\EconumoBundle\Infrastructure\Doctrine\Type\UserPasswordRequestCodeType
            budget_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\BudgetNameType
            budget_folder_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\BudgetFolderNameType
            budget_envelope_name_type: App\EconumoBundle\Infrastructure\Doctrine\Type\BudgetEnvelopeNameType
            budget_element_type: App\EconumoBundle\Infrastructure\Doctrine\Type\BudgetElementType
            decimal_number_type: App\EconumoBundle\Infrastructure\Doctrine\Type\DecimalNumberType
            recurring_interval_type: App\EconumoBundle\Infrastructure\Doctrine\Type\RecurringIntervalType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                type: xml
                dir: '%kernel.project_dir%/src/EconumoBundle/Infrastructure/Doctrine/Entity/mapping'
                prefix: 'App\EconumoBundle\Domain\Entity'
            Infrastructure:
                type: annotation
                dir: '%kernel.project_dir%/src/EconumoBundle/Infrastructure/Doctrine/Entity'
                prefix: 'App\EconumoBundle\Infrastructure\Doctrine\Entity'
